name: 🇨🇳 功能需求（beta）
description: 使用中文 Bug 报告模板提交一个功能需求
title: "[Feature Request] 请替换成合适的标题"
labels: ["💡+Feature+Request"]
body:
  - type: markdown
    attributes:
      value: |
        最后，在开 issue 前，可以先搜索一下以往的旧 issue - 你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。注意：如果你发现一个已经关闭的旧 issue 在最新版本中仍然存在，请不要在旧 issue 下面留言，而应该用下面的表单开一个新的 issue。

        ---
  - type: textarea
    id: needs
    attributes:
      label: 这个功能解决了什么问题？
      description: |
        请尽可能详尽地说明这个需求的用例和场景。最重要的是：解释清楚是怎样的用户体验需求催生了这个功能上的需求。
        Evv Design 的一个重要设计原则是保持 API 的简洁和直接。通常来说，我们只考虑添加在现有的 API 下无法轻松实现的功能。新功能的用例也应当足够常见。
    validations:
      required: true
  - type: textarea
    id: api
    attributes:
      label: 你期望的 API 是怎样的？
      description: |
        描述一下你期望这个新功能的 API 是如何使用的，并提供一些代码示例。请用 Markdown 格式化你的代码片段。
        如果有新的 UI 界面，最好截图展示你期望的界面是什么样的？
      placeholder: |
        ```jsx
        <Drawer extra={<Button />} {...props} />
        ```
    validations:
      required: true
  - type: input
    id: hidden-tag
    attributes:
      label: 其他
      description: 不要删除预填内容，否则 issue 会被自动关闭。
      value: <!-- generated by evv-design-issue-helper. DO NOT REMOVE -->
