name: 🇨🇳 报告缺陷（beta）
description: 使用中文 Bug 报告模板提交一个缺陷
title: "[Bug] 请替换成合适的标题"
labels: ["🐛+Bug"]
body:
  - type: markdown
    attributes:
      value: |
        在开 issue 前，可以先搜索一下以往的旧 issue - 你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。注意：如果你发现一个已经关闭的旧 issue 在最新版本中仍然存在，请不要在旧 issue 下面留言，而应该用下面的表单开一个新的 issue。

        ---
  - type: input
    id: reproduce
    attributes:
      label: 重现链接
      description: 请提供一个尽可能精简的 [codesandbox](https://u.ant.design/codesandbox-repro) 或 [GitHub 仓库](https://github.com/ant-design/create-react-app-antd/) 的链接。[什么是最小化重现，为什么这是必需的？](https://github.com/ant-design/antd-issue-helper/blob/master/src/locales/zh/reproModal.md)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: evv 版本
      description: 你正在使用的 evv 版本是多少？（注意不是 package.json 里的版本，而是 node_modules/@ezviz/evv 里实际安装的版本）
      placeholder: 如 1.1.12
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: 请提供一个傻瓜式的操作步骤，方便我们无脑重现问题。
      placeholder: |
        比如：
        1. 点击重现链接里的主按钮
        2. 等待五秒钟
        3. 观察按钮的边框
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
      placeholder: 比如：按钮样式正常，边框一直存在
    validations:
      required: true
  - type: textarea
    id: reality
    attributes:
      label: 实际的结果是什么？
      placeholder: 比如：按钮样式异常，边框突然丢失
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      description: 在哪些浏览器上能重现这个问题？
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
        - Internet Explorer
        - Others
  - type: input
    id: browsers-version
    attributes:
      label: 浏览器版本
      placeholder: 如：版本 95.0.4638.69（正式版本） (x86_64)
  - type: dropdown
    id: os
    attributes:
      label: 操作系统
      description: 使用的操作系统是？
      options:
        - Windows
        - MacOS
        - iOS
        - Android
        - Others
  - type: input
    id: hidden-tag
    attributes:
      label: 其他
      description: 不要删除预填内容，否则 issue 会被自动关闭。
      value: <!-- generated by evv-design-issue-helper. DO NOT REMOVE -->

